import type { Locale } from "@/components/locale-provider";

export type LocalizedOption = { value: string; labels: Record<Locale, string>; keywords?: string };
const labels = (ko: string, en: string, zh: string, ja: string, vi: string): Record<Locale, string> => ({ ko, en, zh, ja, vi });
const proper = (value: string, label: string): LocalizedOption => ({ value, labels: { ko: label, en: label, zh: label, ja: label, vi: label }, keywords: label });

export const institutionOptions: LocalizedOption[] = [
  proper("kaist", "KAIST · 한국과학기술원"), proper("cnu", "Chungnam National University · 충남대학교"), proper("ust", "UST · 과학기술연합대학원대학교"), proper("hanbat", "Hanbat National University · 국립한밭대학교"), proper("hannam", "Hannam University · 한남대학교"), proper("daejeon-univ", "Daejeon University · 대전대학교"), proper("mokwon", "Mokwon University · 목원대학교"), proper("paichai", "Pai Chai University · 배재대학교"),
  proper("ibs", "Institute for Basic Science (IBS) · 기초과학연구원"), proper("etri", "ETRI · 한국전자통신연구원"), proper("krict", "KRICT · 한국화학연구원"), proper("kimm", "KIMM · 한국기계연구원"), proper("kribb", "KRIBB · 한국생명공학연구원"), proper("kier", "KIER · 한국에너지기술연구원"), proper("kigam", "KIGAM · 한국지질자원연구원"), proper("kriss", "KRISS · 한국표준과학연구원"), proper("kari", "KARI · 한국항공우주연구원"), proper("kaeri", "KAERI · 한국원자력연구원"), proper("kisti", "KISTI · 한국과학기술정보연구원"), proper("kbsi", "KBSI · 한국기초과학지원연구원"), proper("kiom", "KIOM · 한국한의학연구원"), proper("kins", "KINS · 한국원자력안전기술원"), proper("kfe", "KFE · 한국핵융합에너지연구원"), proper("add", "Agency for Defense Development (ADD) · 국방과학연구소"), proper("nnfc", "National NanoFab Center · 나노종합기술원"), proper("other", "Other organization · 기타 기관"),
];

export const researchFieldOptions: LocalizedOption[] = [
  { value:"natural-sciences", labels:labels("자연과학","Natural sciences","自然科学","自然科学","Khoa học tự nhiên") },
  { value:"engineering-technology", labels:labels("공학·기술","Engineering and technology","工程与技术","工学・技術","Kỹ thuật và công nghệ") },
  { value:"medical-health", labels:labels("의학·보건학","Medical and health sciences","医学与健康科学","医学・健康科学","Y học và khoa học sức khỏe") },
  { value:"agricultural-veterinary", labels:labels("농업·수의학","Agricultural and veterinary sciences","农业与兽医学","農学・獣医学","Nông nghiệp và thú y") },
  { value:"social-sciences", labels:labels("사회과학","Social sciences","社会科学","社会科学","Khoa học xã hội") },
  { value:"humanities-arts", labels:labels("인문학·예술","Humanities and the arts","人文与艺术","人文学・芸術","Nhân văn và nghệ thuật") },
  { value:"convergence", labels:labels("융합·다학제 연구","Convergence and multidisciplinary research","融合与跨学科研究","融合・学際研究","Nghiên cứu liên ngành") },
];

export const specialtyOptions: LocalizedOption[] = [
  ["mathematics","수학","Mathematics","数学","数学","Toán học"], ["computer-science","컴퓨터·정보과학","Computer and information sciences","计算机与信息科学","コンピュータ・情報科学","Khoa học máy tính và thông tin"], ["ai","인공지능·머신러닝","Artificial intelligence and machine learning","人工智能与机器学习","人工知能・機械学習","Trí tuệ nhân tạo và máy học"], ["data-hpc","데이터·HPC 과학","Data and HPC science","数据与高性能计算","データ・HPC科学","Dữ liệu và HPC"], ["physics","물리학","Physics","物理学","物理学","Vật lý"], ["chemistry","화학","Chemistry","化学","化学","Hóa học"], ["earth-environment","지구·환경과학","Earth and environmental sciences","地球与环境科学","地球・環境科学","Khoa học trái đất và môi trường"], ["biology","생명과학","Biological sciences","生命科学","生命科学","Khoa học sinh học"],
  ["electrical-information","전기·전자·정보공학","Electrical, electronic and information engineering","电气电子与信息工程","電気電子・情報工学","Điện, điện tử và công nghệ thông tin"], ["mechanical","기계공학","Mechanical engineering","机械工程","機械工学","Kỹ thuật cơ khí"], ["aerospace","항공우주시스템공학","Aerospace systems engineering","航空航天系统工程","航空宇宙システム工学","Kỹ thuật hàng không vũ trụ"], ["civil","건설·토목공학","Civil engineering","土木工程","土木工学","Kỹ thuật xây dựng"], ["chemical-engineering","화학·생명화학공학","Chemical and biomolecular engineering","化学与生物分子工程","化学・生体分子工学","Kỹ thuật hóa học và sinh học phân tử"], ["materials","신소재·재료공학","Materials science and engineering","材料科学与工程","材料科学・工学","Khoa học và kỹ thuật vật liệu"], ["nano","나노기술","Nanotechnology","纳米技术","ナノテクノロジー","Công nghệ nano"], ["robotics","로봇·메카트로닉스","Robotics and mechatronics","机器人与机电一体化","ロボット・メカトロニクス","Robot và cơ điện tử"], ["semiconductor","반도체공학","Semiconductor engineering","半导体工程","半導体工学","Kỹ thuật bán dẫn"], ["quantum","양자과학·양자정보","Quantum science and information","量子科学与信息","量子科学・量子情報","Khoa học và thông tin lượng tử"], ["nuclear","원자력·방사선과학","Nuclear and radiation science","核能与放射科学","原子力・放射線科学","Khoa học hạt nhân và bức xạ"], ["energy","에너지공학","Energy engineering","能源工程","エネルギー工学","Kỹ thuật năng lượng"],
  ["basic-medicine","기초의학","Basic medicine","基础医学","基礎医学","Y học cơ bản"], ["clinical-medicine","임상의학","Clinical medicine","临床医学","臨床医学","Y học lâm sàng"], ["biotechnology","생명공학·의생명","Biotechnology and biomedicine","生物技术与生物医学","生命工学・医学生命科学","Công nghệ sinh học và y sinh"], ["brain-cognitive","뇌·인지과학","Brain and cognitive sciences","脑与认知科学","脳・認知科学","Khoa học não bộ và nhận thức"], ["pharmacy","약학·신약개발","Pharmacy and drug discovery","药学与药物研发","薬学・創薬","Dược học và phát triển thuốc"], ["precision-measurement","정밀측정과학","Precision measurement science","精密测量科学","精密計測科学","Khoa học đo lường chính xác"], ["ocean","해양과학·해양공학","Ocean science and engineering","海洋科学与工程","海洋科学・工学","Khoa học và kỹ thuật biển"], ["agriculture","농업·식품과학","Agricultural and food sciences","农业与食品科学","農学・食品科学","Nông nghiệp và khoa học thực phẩm"], ["economics-business","경제·경영학","Economics and business","经济与管理","経済・経営学","Kinh tế và kinh doanh"], ["policy-administration","정책·행정학","Policy and public administration","政策与公共管理","政策・行政学","Chính sách và hành chính công"], ["psychology","심리학","Psychology","心理学","心理学","Tâm lý học"], ["education","교육학","Education","教育学","教育学","Giáo dục học"], ["humanities","인문학·디지털인문학","Humanities and digital humanities","人文学与数字人文","人文学・デジタル人文学","Nhân văn và nhân văn số"], ["other","기타 세부 전공","Other specialty","其他专业","その他の専門","Chuyên ngành khác"],
].map(([value, ko, en, zh, ja, vi]) => ({ value, labels: labels(ko, en, zh, ja, vi) }));

export const careerStageOptions: LocalizedOption[] = [
  { value:"undergraduate", labels:labels("학부생","Undergraduate student","本科生","学部生","Sinh viên đại học") }, { value:"masters", labels:labels("석사과정","Master's student","硕士生","修士課程","Học viên cao học") }, { value:"doctoral", labels:labels("박사과정","Doctoral student","博士生","博士課程","Nghiên cứu sinh") }, { value:"postdoc", labels:labels("박사후연구원","Postdoctoral researcher","博士后研究员","博士研究員","Nghiên cứu sau tiến sĩ") }, { value:"researcher", labels:labels("연구원","Researcher","研究员","研究員","Nhà nghiên cứu") }, { value:"professor", labels:labels("교수","Professor","教授","教授","Giáo sư") }, { value:"industry", labels:labels("기업 연구자","Industry researcher","企业研究员","企業研究者","Nhà nghiên cứu doanh nghiệp") },
];
